version: '3'

services:
  postgres:  
    image: ankane/pgvector
    networks:
      - default
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=funding
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - 4200:4200
    networks:
      - default
    depends_on:
      - postgres
    env_file:
      - .env
    
volumes:
  pgdata:

networks:
  default:
    driver: bridge
