version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    environment:
      - REDISINSIGHT_HOSTS=redis

  postgres:
    image: ankane/pgvector
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=funding
    volumes:
      - pgdata:/var/lib/postgresql/data  
volumes:
  pgdata: